aws/scylla_login: update rest scylla-ami-setup to new name
We had rename the scylla-ami-setup to scylla-image-setup.
But the old name is still used in aws scylla_login script.

Error:
Traceback (most recent call last):
  File "/opt/scylladb/scylla-machine-image/libexec/scylla_login", line 115, in <module>
    setup = systemd_unit('scylla-ami-setup.service')
  File "/opt/scylladb/scripts/scylla_util.py", line 619, in __init__
    raise SystemdException('unit {} not found'.format(unit))
scylla_util.SystemdException: unit scylla-ami-setup.service not found

Signed-off-by: Amos Kong <amos@scylladb.com>
(cherry picked from commit 6e53476ce36822b2406c6bd87bd0cf49811dc149)